### ISSUE TITLE
Type 'Transform' is not assignable to type 'Writable'.

### ISSUE THREAD

**Issue by smoebody** [weswigham/typed-stream#1]
Hi,

it seems that installing `@types/node` installs your typed-stream version for node's stream type-definition, so maybe you can help me.

i have the following class in my typescript:
```typescript
class MyFileConverter {
	encoder: stream.Transform;

	getWritable(): stream.Writable {
		return this.encoder;
	}
}
```
but appearently typescript gives me an error for that, complaining that '_write' is missing. 

```
Error TS2322: Type 'Transform' is not assignable to type 'Writable'.
  Property '_write' is missing in type 'Transform'.
```

From the docs i assumed that the 'Transform' class is implementing the 'Writable' interface, so this should work, no? Any suggestions?

thanks in advance

**Comment by weswigham** [comment]
No it doesn't - The `npm` package `@types/node` has no dependencies. Its source is located at  https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/node - you can log any issue you have there on DT.
